### ISSUE TITLE
npm does not build webpack

### ISSUE THREAD

**Issue by JoeOM** [BrainCrumbz/AWATTS#3]
C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client>npm run build

> awatts-client@1.3.2 build C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client
> npm run build-dev

> awatts-client@1.3.2 prebuild-dev C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client
> npm run clean

> awatts-client@1.3.2 clean C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client
> rimraf ./buildOutput/* ./codegen/*

> awatts-client@1.3.2 build-dev C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client
> webpack --config ./webpack.config.dev.js --display-error-details --progress --profile --colors
                                                                                                                  14713ms building modules                             4ms add02099ms7221ms asse390ms emitting
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (C:\Users\joben\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (C:\Users\joben\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-dev"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! awatts-client@1.3.2 build-dev: `webpack --config ./webpack.config.dev.js --display-error-details --progress --profile --colors`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the awatts-client@1.3.2 build-dev script 'webpack --config ./webpack.config.dev.js --display-error-details --progress --profile --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the awatts-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config ./webpack.config.dev.js --display-error-details --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs awatts-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls awatts-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\joben\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! awatts-client@1.3.2 build: `npm run build-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the awatts-client@1.3.2 build script 'npm run build-dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the awatts-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs awatts-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls awatts-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\joe\Desktop\Angular2\AWATTS-master\AWATTS-master\src\AWATTS\client\npm-debug.log

Any ideas? Please help - I am trying to setup your solution to learn. Thank you.

**Comment by BrainCrumbz** [comment]
Hi there,
Thanks for trying our starter solution out!

Actually, never saw this error coming. I did some search on the internet, e.g. just for a couple of terms popping out from the error message: *webpack Error This socket is closed*. A couple of results stood out, highlighting a possible issue: 

1. https://github.com/nodejs/node/issues/9542
1. https://github.com/npm/npm/issues/12887

They both mention the problem showing up after switching to node v7.1.0, which incidentally is also the version you seems to be running.

We did not try such node version yet, currently we're on node v6.x (6.2.2 actually). You might want to try again, after uninstalling v7.1, with node v6.x or v7.0 and see if things change.
